### ISSUE TITLE
ImportError: Bad module name in 'pyrocore.torrent.rtorrent:RtorrentEngine' (No module named 'pyrocore')

### ISSUE THREAD

**Issue by newadventure079** [kannibalox/PtpUploader#12]
I ran `ReleaseInfoMaker /Volumes/data/Torrents/complete/CW\ 2008.mp4`

```
2022-01-18 02:05:47,230 INFO  PtpUploader.ReleaseDescriptionFormatter Making release description
2022-01-18 02:05:47,238 INFO  PtpUploader.MyGlobals Making torrent from '/Volumes/data/Torrents/complete/CW 2008.mp4' to '/Volumes/data/Torrents/complete/PTP CW 2008.torrent'.
2022-01-18 02:05:47,239 INFO  pyrosimple.util.metafile.Metafile Creating '/Volumes/data/Torrents/complete/PTP CW 2008.torrent' for data in '/Volumes/data/Torrents/complete/CW 2008.mp4'...
2022-01-18 02:05:48,407 INFO  pyrosimple.util.metafile.Metafile Hashing of 1.3 GiB took 1.2 secs (1.1 GiB/s)
2022-01-18 02:05:48,417 INFO  PtpUploader.MyGlobals Initializing PyroScope.
Traceback (most recent call last):
  File "/Users/.venv/ptpuploader/lib/python3.9/site-packages/pyrosimple/util/pymagic.py", line 55, in import_name
    module = __import__(module_name, globals(), {}, [name])
ModuleNotFoundError: No module named 'pyrocore'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/.venv/ptpuploader/bin/ReleaseInfoMaker", line 8, in <module>
    sys.exit(run())
  File "/Users/.venv/ptpuploader/lib/python3.9/site-packages/PtpUploader/ReleaseInfoMaker.py", line 158, in run
    releaseInfoMaker.MakeReleaseInfo(
  File "/Users/.venv/ptpuploader/lib/python3.9/site-packages/PtpUploader/ReleaseInfoMaker.py", line 132, in MakeReleaseInfo
    MyGlobals.GetTorrentClient().AddTorrentSkipHashCheck(
  File "/Users/.venv/ptpuploader/lib/python3.9/site-packages/PtpUploader/MyGlobals.py", line 70, in GetTorrentClient
    self.TorrentClient = Rtorrent(Settings.TorrentClientAddress)
  File "/Users/.venv/ptpuploader/lib/python3.9/site-packages/PtpUploader/Tool/Rtorrent.py", line 24, in __init__
    load_config.ConfigLoader().load()
  File "/Users/.venv/ptpuploader/lib/python3.9/site-packages/pyrosimple/util/load_config.py", line 237, in load
    self._validate_namespace(namespace)
  File "/Users/.venv/ptpuploader/lib/python3.9/site-packages/pyrosimple/util/load_config.py", line 118, in _validate_namespace
    namespace[factory] = pymagic.import_name(namespace[factory])() if namespace[factory] else None
  File "/Users/.venv/ptpuploader/lib/python3.9/site-packages/pyrosimple/util/pymagic.py", line 57, in import_name
    raise ImportError("Bad module name in %r (%s)" % (module_spec, exc))
ImportError: Bad module name in 'pyrocore.torrent.rtorrent:RtorrentEngine' (No module named 'pyrocore')
```

**Comment by kannibalox** [comment]
Fixed in https://github.com/kannibalox/pyrosimple/commit/b5a58c9d1ce258efff717369b287a34fa2fe6af0, the normal upgrade procedure will automatically get the latest version

**Comment by newadventure079** [comment]
@kannibalox I dont think the pyrosimple dependency updated for me.  I'm still getting the same error.

I did a `git pull` and then `pip3 install .`

```
Processing /Users/Documents/code/PtpUploader
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting imdbpy@ git+https://github.com/alberanid/imdbpy@master
  Cloning https://github.com/alberanid/imdbpy (to revision master) to /private/var/folders/h8/91v0dsdx5c1ckpj1tvp_l8pm0000gn/T/pip-install-5753cvn1/imdbpy_e00a896e2c054b51947e3530470e8b19
  Running command git clone --filter=blob:none -q https://github.com/alberanid/imdbpy /private/var/folders/h8/91v0dsdx5c1ckpj1tvp_l8pm0000gn/T/pip-install-5753cvn1/imdbpy_e00a896e2c054b51947e3530470e8b19
  Resolved https://github.com/alberanid/imdbpy to commit 32938951a28dd77257d091548e09e3da64a64026
  Preparing metadata (setup.py) ... done
Collecting pyrosimple@ https://github.com/kannibalox/pyrosimple/archive/refs/heads/main.tar.gz
  Using cached https://github.com/kannibalox/pyrosimple/archive/refs/heads/main.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: Django<4.0.0,>=3.2.8 in /Users/.venv/ptpuploader/lib/python3.9/site-packages (from ptpuploader==0.9.0) (3.2.11)
Requirement already satisfied: dynaconf<4.0.0,>=3.1.7 in /Users/.venv/ptpuploader/lib/python3.9/site-packages (from ptpuploader==0.9.0) (3.1.7)
Requirement already satisfied: guessit<4.0.0,>=3.3.1 in /Users/.venv/ptpuploader/lib/python3.9/site-packages (from ptpuploader==0.9.0) (3.4.3)
Requirement already satisfied: requests<3.0.0,>=2.26.0 in /Users/.venv/ptpuploader/lib/python3.9/site-packages (from ptpuploader==0.9.0) (2.27.1)
Requirement already satisfied: sqlparse>=0.2.2 in /Users/.venv/ptpuploader/lib/python3.9/site-packages (from Django<4.0.0,>=3.2.8->ptpuploader==0.9.0) (0.4.2)
Requirement already satisfied: pytz in /Users/.venv/ptpuploader/lib/python3.9/site-packages (from Django<4.0.0,>=3.2.8->ptpuploader==0.9.0) (2021.3)
Requirement already satisfied: asgiref<4,>=3.3.2 in /Users/.venv/ptpuploader/lib/python3.9/site-packages (from Django<4.0.0,>=3.2.8->ptpuploader==0.9.0) (3.4.1)
Requirement already satisfied: rebulk>=3.1.0 in /Users/.venv/ptpuploader/lib/python3.9/site-packages (from guessit<4.0.0,>=3.3.1->ptpuploader==0.9.0) (3.1.0)
Requirement already satisfied: babelfish>=0.6.0 in /Users/.venv/ptpuploader/lib/python3.9/site-packages (from guessit<4.0.0,>=3.3.1->ptpuploader==0.9.0) (0.6.0)
Requirement already satisfied: python-dateutil in /Users/.venv/ptpuploader/lib/python3.9/site-packages (from guessit<4.0.0,>=3.3.1->ptpuploader==0.9.0) (2.8.2)
Requirement already satisfied: idna<4,>=2.5 in /Users/.venv/ptpuploader/lib/python3.9/site-packages (from requests<3.0.0,>=2.26.0->ptpuploader==0.9.0) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/.venv/ptpuploader/lib/python3.9/site-packages (from requests<3.0.0,>=2.26.0->ptpuploader==0.9.0) (1.26.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/.venv/ptpuploader/lib/python3.9/site-packages (from requests<3.0.0,>=2.26.0->ptpuploader==0.9.0) (2.0.10)
Requirement already satisfied: certifi>=2017.4.17 in /Users/.venv/ptpuploader/lib/python3.9/site-packages (from requests<3.0.0,>=2.26.0->ptpuploader==0.9.0) (2021.10.8)
Requirement already satisfied: SQLAlchemy in /Users/.venv/ptpuploader/lib/python3.9/site-packages (from imdbpy@ git+https://github.com/alberanid/imdbpy@master->ptpuploader==0.9.0) (1.4.29)
Requirement already satisfied: lxml in /Users/.venv/ptpuploader/lib/python3.9/site-packages (from imdbpy@ git+https://github.com/alberanid/imdbpy@master->ptpuploader==0.9.0) (4.7.1)
Requirement already satisfied: Tempita<0.6.0,>=0.5.2 in /Users/.venv/ptpuploader/lib/python3.9/site-packages (from pyrosimple@ https://github.com/kannibalox/pyrosimple/archive/refs/heads/main.tar.gz->ptpuploader==0.9.0) (0.5.2)
Requirement already satisfied: bencode.py<5.0.0,>=4.0.0 in /Users/.venv/ptpuploader/lib/python3.9/site-packages (from pyrosimple@ https://github.com/kannibalox/pyrosimple/archive/refs/heads/main.tar.gz->ptpuploader==0.9.0) (4.0.0)
Requirement already satisfied: six>=1.5 in /Users/.venv/ptpuploader/lib/python3.9/site-packages (from python-dateutil->guessit<4.0.0,>=3.3.1->ptpuploader==0.9.0) (1.16.0)
Building wheels for collected packages: ptpuploader
  Building wheel for ptpuploader (pyproject.toml) ... done
  Created wheel for ptpuploader: filename=PtpUploader-0.9.0-py3-none-any.whl size=877036 sha256=3af45d05c84b4f06fb144ad312ce5402c4cdcc2f3b1d2da6b5a4a2da4aa4ec98
  Stored in directory: /private/var/folders/h8/91v0dsdx5c1ckpj1tvp_l8pm0000gn/T/pip-ephem-wheel-cache-ul4auga0/wheels/b5/c5/8f/6d464f8476039ba211e8364236ea1c3c8b3d6c67ce265d370a
Successfully built ptpuploader
Installing collected packages: ptpuploader
  Attempting uninstall: ptpuploader
    Found existing installation: ptpuploader 0.9.0
    Uninstalling ptpuploader-0.9.0:
      Successfully uninstalled ptpuploader-0.9.0
Successfully installed ptpuploader-0.9.0
```

Is what I did the correct procedure? Is there a way for me to check what version of pyrosimple I'm on?

**Comment by kannibalox** [comment]
I've decided to stop being lazy and put out an actual release of pyrosimple. The upgrade procedure should actually work correctly this time, and you can check with a `pip freeze` that `pyrosimple==1.1.0`. If for some reason that _still_ doesn't work, `pip install -U git+https://github.com/kannibalox/pyrosimple.git@main` will force install the latest version.
